# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device']

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
          xcodebuild clean build -project MySudoku.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#       env: 
#          destination: ${{ matrix.destination }}

    - name: Test
      run: |
          xcodebuild clean test -project MySudoku.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
#       env: 
#          destination: ${{ matrix.destination }}
