# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        swift: ["5.7.2"]

    steps:
    - uses: actions/checkout@v3
    - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
      with:
        swift-version: ${{ matrix.swift }}
    - name: Build
      run: |
          xcodebuild test -project MySudoku.xcodeproj \
          -scheme MySudoku \
          -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14 Pro Max' \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
#       env: 
#          destination: ${{ matrix.destination }}

#     - name: Test
#       run: |
#           xcodebuild clean test -Ounchecked -project MySudoku.xcodeproj CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination generic/platform=iOS ONLY_ACTIVE_ARCH=NO
#       env: 
#          destination: ${{ matrix.destination }}
