# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
        matrix:
          destination: [platform:iOS Simulator, name:Any iOS Simulator Device]

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: |
          xcodebuild clean build -project MySudoku.xcodeproj -scheme MySudoku -destination "${destination}" CODE_SIGN_IDENTITY="com.thiggs" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
         destination: ${{ matrix.destination }}
    - name: Run tests
      run: |
          xcodebuild clean test -project MySudoku.xcodeproj -scheme MySudokuTests -destination "${destination}" CODE_SIGN_IDENTITY="com.thiggs" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      env: 
       destination: ${{ matrix.destination }}
